server:
  port: 8083
  servlet:
    context-path: /sso
spring:
  datasource:
    username: postgres
    password: 12345678
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
  main:
    allow-bean-definition-overriding: true
  application:
    name: SSO
  cache:
    type: redis
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    # 有密码填密码，没有密码不填
    password:
    # 连接超时时间（ms)
    timeout: 1000ms
    # 高版本springboot中使用jedis或者lettuce
    jedis:
      pool:
        # 连接池最大连接数（负值表示无限制）
        max-active: 8
        # 连接池最大阻塞等待时间（负值无限制)
        max-wait: 5000ms
        # 最大空闲链接数
        max-idle: 8
        # 最小空闲链接数
        min-idle: 0
mybatis:
  type-handlers-package: com.xingjiahe.www.pgsql
  mapper-locations: classpath:mapper/*.xml